export enum OrderStatus {
  NOTCHECKED = 'NOTCHECKED',
  PACKING = 'PACKING',
  OUTOFSTOCK = 'OUTOFSTOCK',
  INPROGRESS = 'INPROGRESS',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
  RETURNEDITEM = 'RETURNEDITEM',
}
